### ISSUE TITLE
General TODO list i guess

### ISSUE THREAD

**Issue by MvonK** [Youareyou64/Scribe#1]
haha have a fancy checklist

- [x] Get the [fork](https://github.com/imayhaveborkedit/discord.py) working 
- [x] Restructure into cogs
- [ ] Implement the STT library
- [ ] Load balancing for background STT transcription
- [x] Fix "ghost voice client" issue
